wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681993562.317819
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      2:
      - 1
      - 41
      - 55
      - 71
      3:
      - 17
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 1
      - 5
